<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $paises = [
            ['pais_id' => 1, 'nombre' => 'México', 'codigo_iso' => 'MX'],
            ['pais_id' => 2, 'nombre' => 'Afganistán', 'codigo_iso' => 'AF'],
            ['pais_id' => 3, 'nombre' => 'Albania', 'codigo_iso' => 'AL'],
            ['pais_id' => 4, 'nombre' => 'Alemania', 'codigo_iso' => 'DE'],
            ['pais_id' => 5, 'nombre' => 'Andorra', 'codigo_iso' => 'AD'],
            ['pais_id' => 6, 'nombre' => 'Angola', 'codigo_iso' => 'AO'],
            ['pais_id' => 7, 'nombre' => 'Antigua y Barbuda', 'codigo_iso' => 'AG'],
            ['pais_id' => 8, 'nombre' => 'Arabia Saudita', 'codigo_iso' => 'SA'],
            ['pais_id' => 9, 'nombre' => 'Argelia', 'codigo_iso' => 'DZ'],
            ['pais_id' => 10, 'nombre' => 'Argentina', 'codigo_iso' => 'AR'],
            ['pais_id' => 11, 'nombre' => 'Armenia', 'codigo_iso' => 'AM'],
            ['pais_id' => 12, 'nombre' => 'Australia', 'codigo_iso' => 'AU'],
            ['pais_id' => 13, 'nombre' => 'Austria', 'codigo_iso' => 'AT'],
            ['pais_id' => 14, 'nombre' => 'Azerbaiyán', 'codigo_iso' => 'AZ'],
            ['pais_id' => 15, 'nombre' => 'Bahamas', 'codigo_iso' => 'BS'],
            ['pais_id' => 16, 'nombre' => 'Bangladés', 'codigo_iso' => 'BD'],
            ['pais_id' => 17, 'nombre' => 'Barbados', 'codigo_iso' => 'BB'],
            ['pais_id' => 18, 'nombre' => 'Baréin', 'codigo_iso' => 'BH'],
            ['pais_id' => 19, 'nombre' => 'Bélgica', 'codigo_iso' => 'BE'],
            ['pais_id' => 20, 'nombre' => 'Belice', 'codigo_iso' => 'BZ'],
            ['pais_id' => 21, 'nombre' => 'Benín', 'codigo_iso' => 'BJ'],
            ['pais_id' => 22, 'nombre' => 'Bielorrusia', 'codigo_iso' => 'BY'],
            ['pais_id' => 23, 'nombre' => 'Birmania', 'codigo_iso' => 'MM'],
            ['pais_id' => 24, 'nombre' => 'Bolivia', 'codigo_iso' => 'BO'],
            ['pais_id' => 25, 'nombre' => 'Bosnia y Herzegovina', 'codigo_iso' => 'BA'],
            ['pais_id' => 26, 'nombre' => 'Botsuana', 'codigo_iso' => 'BW'],
            ['pais_id' => 27, 'nombre' => 'Brasil', 'codigo_iso' => 'BR'],
            ['pais_id' => 28, 'nombre' => 'Brunéi', 'codigo_iso' => 'BN'],
            ['pais_id' => 29, 'nombre' => 'Bulgaria', 'codigo_iso' => 'BG'],
            ['pais_id' => 30, 'nombre' => 'Burkina Faso', 'codigo_iso' => 'BF'],
            ['pais_id' => 31, 'nombre' => 'Burundi', 'codigo_iso' => 'BI'],
            ['pais_id' => 32, 'nombre' => 'Bután', 'codigo_iso' => 'BT'],
            ['pais_id' => 33, 'nombre' => 'Cabo Verde', 'codigo_iso' => 'CV'],
            ['pais_id' => 34, 'nombre' => 'Camboya', 'codigo_iso' => 'KH'],
            ['pais_id' => 35, 'nombre' => 'Camerún', 'codigo_iso' => 'CM'],
            ['pais_id' => 36, 'nombre' => 'Canadá', 'codigo_iso' => 'CA'],
            ['pais_id' => 37, 'nombre' => 'Catar', 'codigo_iso' => 'QA'],
            ['pais_id' => 38, 'nombre' => 'Chad', 'codigo_iso' => 'TD'],
            ['pais_id' => 39, 'nombre' => 'Chile', 'codigo_iso' => 'CL'],
            ['pais_id' => 40, 'nombre' => 'China', 'codigo_iso' => 'CN'],
            ['pais_id' => 41, 'nombre' => 'Chipre', 'codigo_iso' => 'CY'],
            ['pais_id' => 42, 'nombre' => 'Colombia', 'codigo_iso' => 'CO'],
            ['pais_id' => 43, 'nombre' => 'Comoras', 'codigo_iso' => 'KM'],
            ['pais_id' => 44, 'nombre' => 'Congo', 'codigo_iso' => 'CG'],
            ['pais_id' => 45, 'nombre' => 'República Democrática del Congo', 'codigo_iso' => 'CD'],
            ['pais_id' => 46, 'nombre' => 'Corea del Norte', 'codigo_iso' => 'KP'],
            ['pais_id' => 47, 'nombre' => 'Corea del Sur', 'codigo_iso' => 'KR'],
            ['pais_id' => 48, 'nombre' => 'Costa de Marfil', 'codigo_iso' => 'CI'],
            ['pais_id' => 49, 'nombre' => 'Costa Rica', 'codigo_iso' => 'CR'],
            ['pais_id' => 50, 'nombre' => 'Croacia', 'codigo_iso' => 'HR'],
            ['pais_id' => 51, 'nombre' => 'Cuba', 'codigo_iso' => 'CU'],
            ['pais_id' => 52, 'nombre' => 'Dinamarca', 'codigo_iso' => 'DK'],
            ['pais_id' => 53, 'nombre' => 'Dominica', 'codigo_iso' => 'DM'],
            ['pais_id' => 54, 'nombre' => 'Ecuador', 'codigo_iso' => 'EC'],
            ['pais_id' => 55, 'nombre' => 'Egipto', 'codigo_iso' => 'EG'],
            ['pais_id' => 56, 'nombre' => 'El Salvador', 'codigo_iso' => 'SV'],
            ['pais_id' => 57, 'nombre' => 'Emiratos Árabes Unidos', 'codigo_iso' => 'AE'],
            ['pais_id' => 58, 'nombre' => 'Eritrea', 'codigo_iso' => 'ER'],
            ['pais_id' => 59, 'nombre' => 'Eslovaquia', 'codigo_iso' => 'SK'],
            ['pais_id' => 60, 'nombre' => 'Eslovenia', 'codigo_iso' => 'SI'],
            ['pais_id' => 61, 'nombre' => 'España', 'codigo_iso' => 'ES'],
            ['pais_id' => 62, 'nombre' => 'Estados Unidos', 'codigo_iso' => 'US'],
            ['pais_id' => 63, 'nombre' => 'Estonia', 'codigo_iso' => 'EE'],
            ['pais_id' => 64, 'nombre' => 'Etiopía', 'codigo_iso' => 'ET'],
            ['pais_id' => 65, 'nombre' => 'Filipinas', 'codigo_iso' => 'PH'],
            ['pais_id' => 66, 'nombre' => 'Finlandia', 'codigo_iso' => 'FI'],
            ['pais_id' => 67, 'nombre' => 'Fiyi', 'codigo_iso' => 'FJ'],
            ['pais_id' => 68, 'nombre' => 'Francia', 'codigo_iso' => 'FR'],
            ['pais_id' => 69, 'nombre' => 'Gabón', 'codigo_iso' => 'GA'],
            ['pais_id' => 70, 'nombre' => 'Gambia', 'codigo_iso' => 'GM'],
            ['pais_id' => 71, 'nombre' => 'Georgia', 'codigo_iso' => 'GE'],
            ['pais_id' => 72, 'nombre' => 'Ghana', 'codigo_iso' => 'GH'],
            ['pais_id' => 73, 'nombre' => 'Granada', 'codigo_iso' => 'GD'],
            ['pais_id' => 74, 'nombre' => 'Grecia', 'codigo_iso' => 'GR'],
            ['pais_id' => 75, 'nombre' => 'Guatemala', 'codigo_iso' => 'GT'],
            ['pais_id' => 76, 'nombre' => 'Guinea', 'codigo_iso' => 'GN'],
            ['pais_id' => 77, 'nombre' => 'Guinea-Bisáu', 'codigo_iso' => 'GW'],
            ['pais_id' => 78, 'nombre' => 'Guinea Ecuatorial', 'codigo_iso' => 'GQ'],
            ['pais_id' => 79, 'nombre' => 'Guyana', 'codigo_iso' => 'GY'],
            ['pais_id' => 80, 'nombre' => 'Haití', 'codigo_iso' => 'HT'],
            ['pais_id' => 81, 'nombre' => 'Honduras', 'codigo_iso' => 'HN'],
            ['pais_id' => 82, 'nombre' => 'Hungría', 'codigo_iso' => 'HU'],
            ['pais_id' => 83, 'nombre' => 'India', 'codigo_iso' => 'IN'],
            ['pais_id' => 84, 'nombre' => 'Indonesia', 'codigo_iso' => 'ID'],
            ['pais_id' => 85, 'nombre' => 'Irak', 'codigo_iso' => 'IQ'],
            ['pais_id' => 86, 'nombre' => 'Irán', 'codigo_iso' => 'IR'],
            ['pais_id' => 87, 'nombre' => 'Irlanda', 'codigo_iso' => 'IE'],
            ['pais_id' => 88, 'nombre' => 'Islandia', 'codigo_iso' => 'IS'],
            ['pais_id' => 89, 'nombre' => 'Islas Marshall', 'codigo_iso' => 'MH'],
            ['pais_id' => 90, 'nombre' => 'Islas Salomón', 'codigo_iso' => 'SB'],
            ['pais_id' => 91, 'nombre' => 'Israel', 'codigo_iso' => 'IL'],
            ['pais_id' => 92, 'nombre' => 'Italia', 'codigo_iso' => 'IT'],
            ['pais_id' => 93, 'nombre' => 'Jamaica', 'codigo_iso' => 'JM'],
            ['pais_id' => 94, 'nombre' => 'Japón', 'codigo_iso' => 'JP'],
            ['pais_id' => 95, 'nombre' => 'Jordania', 'codigo_iso' => 'JO'],
            ['pais_id' => 96, 'nombre' => 'Kazajistán', 'codigo_iso' => 'KZ'],
            ['pais_id' => 97, 'nombre' => 'Kenia', 'codigo_iso' => 'KE'],
            ['pais_id' => 98, 'nombre' => 'Kirguistán', 'codigo_iso' => 'KG'],
            ['pais_id' => 99, 'nombre' => 'Kiribati', 'codigo_iso' => 'KI'],
            ['pais_id' => 100, 'nombre' => 'Kuwait', 'codigo_iso' => 'KW'],
            ['pais_id' => 101, 'nombre' => 'Laos', 'codigo_iso' => 'LA'],
            ['pais_id' => 102, 'nombre' => 'Lesoto', 'codigo_iso' => 'LS'],
            ['pais_id' => 103, 'nombre' => 'Letonia', 'codigo_iso' => 'LV'],
            ['pais_id' => 104, 'nombre' => 'Líbano', 'codigo_iso' => 'LB'],
            ['pais_id' => 105, 'nombre' => 'Liberia', 'codigo_iso' => 'LR'],
            ['pais_id' => 106, 'nombre' => 'Libia', 'codigo_iso' => 'LY'],
            ['pais_id' => 107, 'nombre' => 'Liechtenstein', 'codigo_iso' => 'LI'],
            ['pais_id' => 108, 'nombre' => 'Lituania', 'codigo_iso' => 'LT'],
            ['pais_id' => 109, 'nombre' => 'Luxemburgo', 'codigo_iso' => 'LU'],
            ['pais_id' => 110, 'nombre' => 'Macedonia del Norte', 'codigo_iso' => 'MK'],
            ['pais_id' => 111, 'nombre' => 'Madagascar', 'codigo_iso' => 'MG'],
            ['pais_id' => 112, 'nombre' => 'Malasia', 'codigo_iso' => 'MY'],
            ['pais_id' => 113, 'nombre' => 'Malaui', 'codigo_iso' => 'MW'],
            ['pais_id' => 114, 'nombre' => 'Maldivas', 'codigo_iso' => 'MV'],
            ['pais_id' => 115, 'nombre' => 'Malí', 'codigo_iso' => 'ML'],
            ['pais_id' => 116, 'nombre' => 'Malta', 'codigo_iso' => 'MT'],
            ['pais_id' => 117, 'nombre' => 'Marruecos', 'codigo_iso' => 'MA'],
            ['pais_id' => 118, 'nombre' => 'Mauricio', 'codigo_iso' => 'MU'],
            ['pais_id' => 119, 'nombre' => 'Mauritania', 'codigo_iso' => 'MR'],
            ['pais_id' => 120, 'nombre' => 'Micronesia', 'codigo_iso' => 'FM'],
            ['pais_id' => 121, 'nombre' => 'Moldavia', 'codigo_iso' => 'MD'],
            ['pais_id' => 122, 'nombre' => 'Mónaco', 'codigo_iso' => 'MC'],
            ['pais_id' => 123, 'nombre' => 'Mongolia', 'codigo_iso' => 'MN'],
            ['pais_id' => 124, 'nombre' => 'Montenegro', 'codigo_iso' => 'ME'],
            ['pais_id' => 125, 'nombre' => 'Mozambique', 'codigo_iso' => 'MZ'],
            ['pais_id' => 126, 'nombre' => 'Namibia', 'codigo_iso' => 'NA'],
            ['pais_id' => 127, 'nombre' => 'Nauru', 'codigo_iso' => 'NR'],
            ['pais_id' => 128, 'nombre' => 'Nepal', 'codigo_iso' => 'NP'],
            ['pais_id' => 129, 'nombre' => 'Nicaragua', 'codigo_iso' => 'NI'],
            ['pais_id' => 130, 'nombre' => 'Níger', 'codigo_iso' => 'NE'],
            ['pais_id' => 131, 'nombre' => 'Nigeria', 'codigo_iso' => 'NG'],
            ['pais_id' => 132, 'nombre' => 'Noruega', 'codigo_iso' => 'NO'],
            ['pais_id' => 133, 'nombre' => 'Nueva Zelanda', 'codigo_iso' => 'NZ'],
            ['pais_id' => 134, 'nombre' => 'Omán', 'codigo_iso' => 'OM'],
            ['pais_id' => 135, 'nombre' => 'Países Bajos', 'codigo_iso' => 'NL'],
            ['pais_id' => 136, 'nombre' => 'Pakistán', 'codigo_iso' => 'PK'],
            ['pais_id' => 137, 'nombre' => 'Palaos', 'codigo_iso' => 'PW'],
            ['pais_id' => 138, 'nombre' => 'Panamá', 'codigo_iso' => 'PA'],
            ['pais_id' => 139, 'nombre' => 'Papúa Nueva Guinea', 'codigo_iso' => 'PG'],
            ['pais_id' => 140, 'nombre' => 'Paraguay', 'codigo_iso' => 'PY'],
            ['pais_id' => 141, 'nombre' => 'Perú', 'codigo_iso' => 'PE'],
            ['pais_id' => 142, 'nombre' => 'Polonia', 'codigo_iso' => 'PL'],
            ['pais_id' => 143, 'nombre' => 'Portugal', 'codigo_iso' => 'PT'],
            ['pais_id' => 144, 'nombre' => 'Reino Unido', 'codigo_iso' => 'GB'],
            ['pais_id' => 145, 'nombre' => 'República Centroafricana', 'codigo_iso' => 'CF'],
            ['pais_id' => 146, 'nombre' => 'República Checa', 'codigo_iso' => 'CZ'],
            ['pais_id' => 147, 'nombre' => 'República Dominicana', 'codigo_iso' => 'DO'],
            ['pais_id' => 148, 'nombre' => 'Ruanda', 'codigo_iso' => 'RW'],
            ['pais_id' => 149, 'nombre' => 'Rumania', 'codigo_iso' => 'RO'],
            ['pais_id' => 150, 'nombre' => 'Rusia', 'codigo_iso' => 'RU'],
            ['pais_id' => 151, 'nombre' => 'Samoa', 'codigo_iso' => 'WS'],
            ['pais_id' => 152, 'nombre' => 'San Cristóbal y Nieves', 'codigo_iso' => 'KN'],
            ['pais_id' => 153, 'nombre' => 'San Marino', 'codigo_iso' => 'SM'],
            ['pais_id' => 154, 'nombre' => 'San Vicente y las Granadinas', 'codigo_iso' => 'VC'],
            ['pais_id' => 155, 'nombre' => 'Santa Lucía', 'codigo_iso' => 'LC'],
            ['pais_id' => 156, 'nombre' => 'Santo Tomé y Príncipe', 'codigo_iso' => 'ST'],
            ['pais_id' => 157, 'nombre' => 'Senegal', 'codigo_iso' => 'SN'],
            ['pais_id' => 158, 'nombre' => 'Serbia', 'codigo_iso' => 'RS'],
            ['pais_id' => 159, 'nombre' => 'Seychelles', 'codigo_iso' => 'SC'],
            ['pais_id' => 160, 'nombre' => 'Sierra Leona', 'codigo_iso' => 'SL'],
            ['pais_id' => 161, 'nombre' => 'Singapur', 'codigo_iso' => 'SG'],
            ['pais_id' => 162, 'nombre' => 'Siria', 'codigo_iso' => 'SY'],
            ['pais_id' => 163, 'nombre' => 'Somalia', 'codigo_iso' => 'SO'],
            ['pais_id' => 164, 'nombre' => 'Sri Lanka', 'codigo_iso' => 'LK'],
            ['pais_id' => 165, 'nombre' => 'Suazilandia', 'codigo_iso' => 'SZ'],
            ['pais_id' => 166, 'nombre' => 'Sudáfrica', 'codigo_iso' => 'ZA'],
            ['pais_id' => 167, 'nombre' => 'Sudán', 'codigo_iso' => 'SD'],
            ['pais_id' => 168, 'nombre' => 'Sudán del Sur', 'codigo_iso' => 'SS'],
            ['pais_id' => 169, 'nombre' => 'Suecia', 'codigo_iso' => 'SE'],
            ['pais_id' => 170, 'nombre' => 'Suiza', 'codigo_iso' => 'CH'],
            ['pais_id' => 171, 'nombre' => 'Surinam', 'codigo_iso' => 'SR'],
            ['pais_id' => 172, 'nombre' => 'Tailandia', 'codigo_iso' => 'TH'],
            ['pais_id' => 173, 'nombre' => 'Tanzania', 'codigo_iso' => 'TZ'],
            ['pais_id' => 174, 'nombre' => 'Tayikistán', 'codigo_iso' => 'TJ'],
            ['pais_id' => 175, 'nombre' => 'Timor Oriental', 'codigo_iso' => 'TL'],
            ['pais_id' => 176, 'nombre' => 'Togo', 'codigo_iso' => 'TG'],
            ['pais_id' => 177, 'nombre' => 'Tonga', 'codigo_iso' => 'TO'],
            ['pais_id' => 178, 'nombre' => 'Trinidad y Tobago', 'codigo_iso' => 'TT'],
            ['pais_id' => 179, 'nombre' => 'Túnez', 'codigo_iso' => 'TN'],
            ['pais_id' => 180, 'nombre' => 'Turkmenistán', 'codigo_iso' => 'TM'],
            ['pais_id' => 181, 'nombre' => 'Turquía', 'codigo_iso' => 'TR'],
            ['pais_id' => 182, 'nombre' => 'Tuvalu', 'codigo_iso' => 'TV'],
            ['pais_id' => 183, 'nombre' => 'Ucrania', 'codigo_iso' => 'UA'],
            ['pais_id' => 184, 'nombre' => 'Uganda', 'codigo_iso' => 'UG'],
            ['pais_id' => 185, 'nombre' => 'Uruguay', 'codigo_iso' => 'UY'],
            ['pais_id' => 186, 'nombre' => 'Uzbekistán', 'codigo_iso' => 'UZ'],
            ['pais_id' => 187, 'nombre' => 'Vanuatu', 'codigo_iso' => 'VU'],
            ['pais_id' => 188, 'nombre' => 'Ciudad del Vaticano', 'codigo_iso' => 'VA'],
            ['pais_id' => 189, 'nombre' => 'Venezuela', 'codigo_iso' => 'VE'],
            ['pais_id' => 190, 'nombre' => 'Vietnam', 'codigo_iso' => 'VN'],
            ['pais_id' => 191, 'nombre' => 'Yemen', 'codigo_iso' => 'YE'],
            ['pais_id' => 192, 'nombre' => 'Yibuti', 'codigo_iso' => 'DJ'],
            ['pais_id' => 193, 'nombre' => 'Zambia', 'codigo_iso' => 'ZM'],
            ['pais_id' => 194, 'nombre' => 'Zimbabue', 'codigo_iso' => 'ZW'],
            ['pais_id' => 195, 'nombre' => 'Palestina', 'codigo_iso' => 'PS'],
            ['pais_id' => 196, 'nombre' => 'Kosovo', 'codigo_iso' => 'XK'],
        ];

        foreach ($paises as $pais) {
            DB::table('paises')->insert([
                'pais_id' => $pais['pais_id'],
                'nombre' => $pais['nombre'],
                'codigo_iso' => $pais['codigo_iso'],
                'estado' => 'A',
                'fecha_registro' => now(),
            ]);
        }
    }
}