<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProveedoresSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $proveedores = [
            [   'nombre' => 'RADIOMOVIL DIPSA SA DE CV', 
                'tipo' => 'EMPRESA', 
                'rfc' => 'RDI841003QJ4', 
                'direccion' => 'Lago Zurich No 245 Edif Telcel',
                'colonia' => 'Col Ampliación Granada', 
                'codigo_postal' => '11529',
                'municipio_id' => 845, 
                'estado_pais_id' => 17, 
                'telefono' => 'Tel. 5525813700',
                'sitio_web' => 'https://empresas.mitelcel.com/',
                'notas_adicionales' => 'Servicios: TELEFONIA',
            ],
            [   'nombre' => 'TOTAL PLAY TELECOMUNICACIONES S.A.P.I. DE C.V.', 
                'tipo' => 'EMPRESA', 
                'rfc' => 'TPT890516JP5', 
                'direccion' => 'AV. SAN JERONIMO 252-PISO 6',
                'colonia' => 'COL LA OTRA BANDA', 
                'codigo_postal' => '4519',
                'municipio_id' => 838, 
                'estado_pais_id' => 17, 
                'telefono' => null,
                'sitio_web' => '',
                'notas_adicionales' => 'PRODUCTOS: INTERNET, Municipio: DEL. COYOACAN',
            ],
            [   'nombre' => 'Efectivale S. de R.L. de C.V.', 
                'tipo' => 'EMPRESA', 
                'rfc' => 'EFE-890801-5L3', 
                'direccion' => 'Saltillo No. 19, 5° Piso',
                'colonia' => 'Col. Condesa', 
                'codigo_postal' => '06140',
                'municipio_id' => null, 
                'estado_pais_id' => null, 
                'telefono' => null,
                'sitio_web' => 'https://www.efectivale.com.mx/efectinet/login',
                'notas_adicionales' => 'Productos: GASOLINA, Municipio: Delegación Cuauhtémoc',
            ],
            [   'nombre' => 'EDENRED MÉXICO', 
                'tipo' => 'EMPRESA', 
                'rfc' => 'ASE930924SS7', 
                'direccion' => 'Lago Rodolfo 29',
                'colonia' => 'Granada', 
                'codigo_postal' => '11520',
                'municipio_id' => 845, 
                'estado_pais_id' => 17, 
                'telefono' => '55 5262 8800',
                'sitio_web' => 'www.edenred.com.mx',
                'notas_adicionales' => 'Productos: GASOLINA',
            ],
            [   'nombre' => 'JESUS OLIVARES', 
                'tipo' => 'PERSONA', 
                'rfc' => '', 
                'direccion' => null,
                'colonia' => '', 
                'codigo_postal' => '',
                'municipio_id' => null, 
                'estado_pais_id' => null, 
                'telefono' => null,
                'sitio_web' => null,
                'notas_adicionales' => 'Servicios: CONTABILIDAD',
            ],
            [   'nombre' => 'SORVEN SC', 
                'tipo' => 'EMPRESA', 
                'rfc' => '', 
                'direccion' => 'NEWTON No. 53 Int: 3',
                'colonia' => 'Col. POLANCO IV SECCION', 
                'codigo_postal' => '11560',
                'municipio_id' => 845, 
                'estado_pais_id' => 17, 
                'telefono' => null,
                'sitio_web' => '',
                'notas_adicionales' => 'Servicios: LEGAL',
            ],
            [   'nombre' => 'MT LAW ABOGADOS', 
                'tipo' => 'EMPRESA', 
                'rfc' => 'MTA210630BB2', 
                'direccion' => null,
                'colonia' => '', 
                'codigo_postal' => '1900',
                'municipio_id' => null, 
                'estado_pais_id' => null, 
                'telefono' => null,
                'sitio_web' => '',
                'notas_adicionales' => 'Servicios: LEGAL',
            ],
            [   'nombre' => 'Rogelio Aguilar Rogel', 
                'tipo' => 'EMPRESA', 
                'rfc' => 'AURR780630261', 
                'direccion' => 'Av Prolongación División del Norte 80',
                'colonia' => '', 
                'codigo_postal' => '14380',
                'municipio_id' => 848, 
                'estado_pais_id' => 17, 
                'telefono' => null,
                'sitio_web' => 'https://www.asicom.mx/',
                'notas_adicionales' => 'Servicios: TI',
            ],
            [   'nombre' => 'GPSCONTROL', 
                'tipo' => 'EMPRESA', 
                'rfc' => 'GPS220218C82', 
                'direccion' => null,
                'colonia' => '', 
                'codigo_postal' => '',
                'municipio_id' => null, 
                'estado_pais_id' => null, 
                'telefono' => null,
                'sitio_web' => '',
                'notas_adicionales' => 'Productos: GPS',
            ],
            [   'nombre' => 'INGENIERIA Y ASESORIA TECNICA INTEGRAL', 
                'tipo' => 'EMPRESA', 
                'rfc' => 'IAT060418TG4', 
                'direccion' => 'TIHUATLAN  8  LOCALIDAD MEXICO',
                'colonia' => 'SAN JERONIMO ACULCO', 
                'codigo_postal' => '10400',
                'municipio_id' => 844, 
                'estado_pais_id' => 17, 
                'telefono' => null,
                'sitio_web' => '',
                'notas_adicionales' => '',
            ],
            [   'nombre' => 'PETROGAS CORPORATION', 
                'tipo' => 'EMPRESA', 
                'rfc' => 'PCO140710BM2', 
                'direccion' => 'Rómulo Garza 212',
                'colonia' => 'Hacienda los Morales Sector 1', 
                'codigo_postal' => '66495',
                'municipio_id' => 914, 
                'estado_pais_id' => 19, 
                'telefono' => '(81) 8305-0800',
                'sitio_web' => 'https://www.petrogas.com.mx/',
                'notas_adicionales' => 'Productos: LUMINARIAS',
            ],
            [   'nombre' => 'CRISTALES Y LUMINARIAS & SOLUCION INTEGRAL EN OBRA CIVIL ', 
                'tipo' => 'EMPRESA', 
                'rfc' => '', 
                'direccion' => 'No. 193 Int. 600 A.',
                'colonia' => 'Ciudad Satelite', 
                'codigo_postal' => '53100',
                'municipio_id' => 636, 
                'estado_pais_id' => 14, 
                'telefono' => null,
                'sitio_web' => '',
                'notas_adicionales' => 'Productos: LUMINARIAS',
                // 	LUMINARIAS
            ],
            [   'nombre' => 'GERARDO BARAJAS', 
                'tipo' => 'PERSONA', 
                'rfc' => '', 
                'direccion' => null,
                'colonia' => '', 
                'codigo_postal' => '',
                'municipio_id' => 636, 
                'estado_pais_id' => 14, 
                'telefono' => null,
                'sitio_web' => '',
                'notas_adicionales' => 'Servicios: OBRA',
                // 	OBRA
            ],
            [   'nombre' => 'CORTINAS MORENO', 
                'tipo' => 'EMPRESA', 
                'rfc' => 'CMO1502263C9', 
                'direccion' => 'Avenida Jadines de Morelos No. 213 LT 28 y 29',
                'colonia' => 'Jadines de Morelos Seccion Bosques', 
                'codigo_postal' => '55070',
                'municipio_id' => 611, 
                'estado_pais_id' => 14, 
                'telefono' => null,
                'sitio_web' => '',
                'notas_adicionales' => 'Productos: CORTINAS',
                // 	CORTINAS
            ],
            // 	Ecatepec de Morelos 	ECATEPEC DE MORELOS 		 		
            [   'nombre' => 'PLOMERIA GARCIA DE MONTERREY', 
                'tipo' => 'EMPRESA', 
                'rfc' => 'PGM720701480', 
                'direccion' => 'Francisco I. Madero 1031 Pte',
                'colonia' => 'Monterrey Centro', 
                'codigo_postal' => '64000',
                'municipio_id' => 908, 
                'estado_pais_id' => 19, 
                'telefono' => '(81) 1970 7913',
                'sitio_web' => 'https://plomeriagarcia.com.mx/',
                'notas_adicionales' => 'Servicios: PLOMERIA',
                // 	PLOMERIA
            ],	 		
            [   'nombre' => 'MOBILIARIO EN MOVIMIENTO', 
                'tipo' => 'EMPRESA', 
                'rfc' => 'MMO0302038C9', 
                'direccion' => 'Pochtecas No. 35',
                'colonia' => 'Paseos de Churubusco', 
                'codigo_postal' => '09030',
                'municipio_id' => 843, 
                'estado_pais_id' => 17, 
                'telefono' => 'CEL. 5535058583',
                'sitio_web' => 'https://mobiliarioenmovimiento.com/',
                'notas_adicionales' => 'Productos: SILLAS',
                // 	SILLAS
            ],
            // 	Iztapalapa 				
            [   'nombre' => 'KENIA ARGELIA AGUIÑAGA GARCIA', 
                'tipo' => 'PERSONA', 
                'rfc' => 'AUGK9012202PA', 
                'direccion' => null,
                'colonia' => '', 
                'codigo_postal' => '',
                'municipio_id' => null, 
                'estado_pais_id' => null, 
                'telefono' => 'CEL. 5522415157',
                'sitio_web' => '',
                // 	BLANCOS
            ],
            [   'nombre' => 'VIMCALL - TEC', 
                'tipo' => 'EMPRESA', 
                'rfc' => 'VIM220712DLA', 
                'direccion' => null,
                'colonia' => '', 
                'codigo_postal' => '',
                'municipio_id' => null, 
                'estado_pais_id' => null, 
                'telefono' => null,
                'sitio_web' => 'https://vimcall-tec.com/',
            ],
            [   'nombre' => 'KASIA MUEBLES', 
                'tipo' => 'EMPRESA', 
                'rfc' => 'KMU220615EZ3', 
                'direccion' => 'AV. ESTADO DE MEXICO 11 C-1',
                'colonia' => 'PROFESOR CRISTOBAL HIGUERA', 
                'codigo_postal' => '52940',
                'municipio_id' => 636, 
                'estado_pais_id' => 14, 
                'telefono' => 'CEL. 5587178953',
                'sitio_web' => 'https://kasiamuebles.com/',
                'notas_adicionales' => 'Productos: SILLONES',
                // 	SILLONES
            ],
            [   'nombre' => 'ALEJANDRA NAVARRO REYES', 
                'tipo' => 'PERSONA', 
                'rfc' => '', 
                'direccion' => 'Calle 41 51 U  Hab.',
                'colonia' => 'Santa Cruz Meyehualco', 
                'codigo_postal' => '09290',
                'municipio_id' => 843, 
                'estado_pais_id' => 17, 
                'telefono' => 'CEL 5537008838',
                'sitio_web' => '',
                // 	BLANCOS
            ],
            [   'nombre' => 'FORZA MUEBLES', 
                'tipo' => 'EMPRESA', 
                'rfc' => 'FMU140306FH0', 
                'direccion' => 'Estebal Loera No. 385',
                'colonia' => 'Oblatos', 
                'codigo_postal' => '44700',
                'municipio_id' => 501, 
                'estado_pais_id' => 13, 
                'telefono' => 'TEL. 36184694',
                'sitio_web' => 'https://muebleslf.com',
                'notas_adicionales' => 'Productos: SILLAS',
                // 	SILLAS
            ],
            [   'nombre' => 'INDUSTRIAS UNIFILA', 
                'tipo' => 'EMPRESA', 
                'rfc' => 'IUN950102S57', 
                'direccion' => 'Francisco I. Madero No. 138',
                'colonia' => 'San Esteban', 
                'codigo_postal' => '53550',
                'municipio_id' => 636, 
                'estado_pais_id' => 14, 
                'telefono' => null,
                'sitio_web' => 'https://www.unifila.com.mx/',
                'notas_adicionales' => 'Productos: UNIFILAS',
                // 	UNIFILAS
            ],
            [   'nombre' => 'SELCA ILUMINACION', 
                'tipo' => 'EMPRESA', 
                'rfc' => 'SIL930127A54', 
                'direccion' => 'Victoria No. 24',
                'colonia' => 'Col. Centro', 
                'codigo_postal' => '06050',
                'municipio_id' => 840, 
                'estado_pais_id' => 17, 
                'telefono' => 'CEL. 5510902341',
                'sitio_web' => 'https://selcailuminacion.com.mx/',
                'notas_adicionales' => 'Productos: MATERIAL ELECTRICO',
                // 	MATERIAL ELECTRICO
            ],
            [   'nombre' => 'TOUCH LABS MEXICO', 
                'tipo' => 'EMPRESA', 
                'rfc' => 'TLM120717DA1', 
                'direccion' => 'Torre Esmerala I, Piso 23Blvd. Manuel Avila Camacho  40',
                'colonia' => 'Lomas de Chapultepec', 
                'codigo_postal' => '11000',
                'municipio_id' => 845, 
                'estado_pais_id' => 17, 
                'telefono' => 'CEL. 5554910745 TEL. 5596286277',
                'sitio_web' => 'https://www.smtouch.mx/',
                'notas_adicionales' => 'Productos: PANTALLAS',
                // 	PANTALLAS
            ],
            [   'nombre' => 'CASA EASTER', 
                'tipo' => 'EMPRESA', 
                'rfc' => '', 
                'direccion' => '237 Privada Acalotenco',
                'colonia' => 'San Sebastian', 
                'codigo_postal' => '02510',
                'municipio_id' => 836, 
                'estado_pais_id' => 17, 
                'telefono' => 'CEL. 5655552155 / 5541381351',
                'sitio_web' => 'https://casaeaster.com/',
                'notas_adicionales' => 'Productos: MUEBLES GENERALES',
                // 	MUEBLES GENERAL
            ],
            [   'nombre' => 'KINGSTRONG NOGAL BEAT', 
                'tipo' => 'EMPRESA', 
                'rfc' => '', 
                'direccion' => 'Dante Alighieri No. 489',
                'colonia' => 'Vallarta Universidad', 
                'codigo_postal' => '45110',
                'municipio_id' => null, // Zopopan
                'estado_pais_id' => null, // Jalisco (13)
                'telefono' => 'CEL. 3312486428',
                'sitio_web' => 'https://nogalbeat.com/',
                'notas_adicionales' => 'Productos: MUEBLES DE OFICINA, falta agregar el Municipio: Zopopan y el Estado: Jalisco',
                // 	MOBILIARIO DE OFICINA
            ],
            [   'nombre' => 'OFFIHO', 
                'tipo' => 'EMPRESA', 
                'rfc' => '', 
                'direccion' => 'Cuitlahuac No. 133',
                'colonia' => 'Barragan y Hernandez', 
                'codigo_postal' => '44450',
                'municipio_id' => 501, 
                'estado_pais_id' => 13, 
                'telefono' => 'CEL. 3319472192',
                'sitio_web' => 'https://offiho.com',
                'notas_adicionales' => 'Productos: SILLAS',
                // 	
            ],
            [   'nombre' => 'SABLON', 
                'tipo' => 'EMPRESA', 
                'rfc' => 'ASA8308231MA', 
                'direccion' => 'Av. Tlahuac No. 84',
                'colonia' => 'Santa Isabel Industrial', 
                'codigo_postal' => '09820',
                'municipio_id' => 843, 
                'estado_pais_id' => 17, 
                'telefono' => 'CEL. 5540101616',
                'sitio_web' => 'https://www.sablon.com.mx/',
                'notas_adicionales' => 'Productos: BOTES DE BASURA',
                // 	
            ],
            [   'nombre' => ' OPULENICIA DECOR', 
                'tipo' => 'EMPRESA', 
                'rfc' => '', 
                'direccion' => 'Calle Hidalgo No. 8',
                'colonia' => 'El Verde', 
                'codigo_postal' => '',
                'municipio_id' => 496, 
                'estado_pais_id' => 13, 
                'telefono' => null,
                'sitio_web' => '',
            ],
            [   'nombre' => 'MAHA HOME DE MEXICO', 
                'tipo' => 'EMPRESA', 
                'rfc' => 'MHM201125', 
                'direccion' => 'Antigua a San Pedro 755 - 4',
                'colonia' => 'Ejido Ana', 
                'codigo_postal' => '27018',
                'municipio_id' => 213, 
                'estado_pais_id' => 7, 
                'telefono' => 'TEL. 528-714-5711 / CEL. 5588983730',
                'sitio_web' => 'https://maha.com.mx/',
                'notas_adicionales' => 'Productos: UTENCILIOS DE COCINA',
            ],
            [   'nombre' => 'CAOCAO', 
                'tipo' => 'EMPRESA', 
                'rfc' => '', 
                'direccion' => null,
                'colonia' => '', 
                'codigo_postal' => '',
                'municipio_id' => null, 
                'estado_pais_id' => null, 
                'telefono' => 'CEL. 3316061293 / TEL. 9995753534',
                'sitio_web' => 'http://shopcaocao.com',
                'notas_adicionales' => 'Productos: LAMBRIN Y DECK',
            ],
            [   'nombre' => 'DECOARQ', 
                'tipo' => 'EMPRESA', 
                'rfc' => '', 
                'direccion' => 'Viaducto Tlalpan 1008 Local 4',
                'colonia' => 'Villa Lázaro Cardenas', 
                'codigo_postal' => '14370',
                'municipio_id' => 848, 
                'estado_pais_id' => 17, 
                'telefono' => 'CEL. 5519596830',
                'sitio_web' => 'http://www.decoarq.mx/index.php/store',
                'notas_adicionales' => 'Servicios: DECORACION ARQUITECTONICA',
            ],
            [   'nombre' => 'NORVID', 
                'tipo' => 'EMPRESA', 
                'rfc' => '', 
                'direccion' => 'Damas 49',
                'colonia' => 'San Jose Insurgentes', 
                'codigo_postal' => '03900',
                'municipio_id' => 837, 
                'estado_pais_id' => 17, 
                'telefono' => 'CEL. 5518027009',
                'sitio_web' => 'https://norvid.com.mx/',
                'notas_adicionales' => 'Productos: MOBILIARIO CORPORATIVO',
                // 	
            ],
            [   'nombre' => 'MURBAN', 
                'tipo' => 'EMPRESA', 
                'rfc' => '', 
                'direccion' => 'Loma Dorada No. 100, Col.',
                'colonia' => 'Bellas Lomas', 
                'codigo_postal' => '78210',
                'municipio_id' => 1711, 
                'estado_pais_id' => 24, 
                'telefono' => null,
                'sitio_web' => '',
                'notas_adicionales' => 'Productos: MOBILIARIO URBANO',
                // 	
            ],
        ];

        foreach ($proveedores as $proveedor) {
            DB::table('proveedores')->insert([
                'nombre' => $proveedor['nombre'],
                'tipo' => $proveedor['tipo'],
                'rfc' => $proveedor['rfc'] ?? 'PENDIENTE',
                'direccion' => $proveedor['direccion'] ?? 'INFORMACION PENDIENTE',
                'colonia' => $proveedor['colonia'],
                'codigo_postal' => $proveedor['codigo_postal'],
                'municipio_id' => $proveedor['municipio_id'] ?? null,
                'estado_pais_id' => $proveedor['estado_pais_id'] ?? null,
                'telefono' => $proveedor['telefono'] ?? 'PENDIENTE',
                'sitio_web' => $proveedor['sitio_web'],
                'notas_adicionales' => $proveedor['notas_adicionales'] ?? null,
                'usuario_id' => $proveedor['usuario_id'] ?? 1,
                'estado' => 'A',
                'fecha_registro' => now(),
            ]);
        }
    }
}
